language: objective-c

osx_image: xcode8
xcode_sdk: iphonesimulator10.0

xcode_project: NapySlider.xcodeproj
xcode_scheme: NapySlider

notifications:
  slack:
    rooms:
      - naptics:0jvqNePbU1ycOfefKuHZ3A6o
    on_success: change
    on_failure: always
  email: false

script: set -o pipefail && xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build | xcpretty -c
